export const copy = {
  greetingSuffix: "",
  tagline: "Build your day.",
  subtitle: "One calm place for your work, health, learning and life.",
  oneThingAtATime: "One thing at a time.",
  onTrack: "You're on track.",
  nextUp: "Next up.",
  takeBreak: "Take a break.",
  dayComplete: "Day complete.",
  niceWork: "Nice work.",
  tomorrow: "Tomorrow is another day.",
  emptyToday: "Nothing scheduled. Enjoy the quiet.",
  emptyHabits: "No habits yet. Add one you want to keep.",
  emptyGoals: "No goals yet. Start with one that matters.",
  emptyTimeline: "Your day is wide open.",
  allCaughtUp: "All caught up.",
  focusStart: "One thing at a time.",
  focusComplete: "Nice work.",
} as const;
